"""
Django settings for WMAD_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$o(!=e4(-06&ttx*5w-+rv@6ol8z-e_wp%37#$8v+gk)3g_49t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web_app',
    'control_panel',
    'admin_site',
]

# 2024-06 Addition: Maintenance Mode Setting
MAINTENANCE_MODE = False                # Set to True to enable maintenance mode

# 2024-06 Addition: Middleware for Maintenance Mode Handling
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'control_panel.middleware.MaintenanceMiddleware',               # Custom middleware for maintenance mode
    'admin_site.middleware.AdminSiteSessionMiddleware',                 # Custom middleware for admin session handling
]

ROOT_URLCONF = 'WMAD_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WMAD_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

    # remove common password and similar to usrname password.
]


# Email Backend Configuration for Development
# During development, emails will be printed to the console. In production, configure an appropriate email backend.
# https://docs.djangoproject.com/en/5.2/topics/email/#email-backends
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect URLs after login/logout
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

# Logging Configuration for Control Panel
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'control_panel_format': {
            'format': '[{asctime}] {message}',
            'style': '{',
        },
    },

    'handlers': {
        'control_panel_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'control_panel.log'),
            'formatter': 'control_panel_format',
        },
    },

    'loggers': {
        'control_panel': {
            'handlers': ['control_panel_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Super maintenance mode password (for future use)
SUPER_MAINTENANCE_PASSWORD = "super_secret_key2025"

MAINTENANCE_ALERT_EMAILS = [            # list of emails to notify when maintenance mode is toggled
    "toushal37@gmail.com",
    # "owner2@example.com",
]

# Custom User Model Setting
AUTH_USER_MODEL = 'web_app.Users'

ADMIN_SITE_SESSION_COOKIE_NAME = "admin_sessionid"  # Custom session cookie name for admin site

SESSION_SAVE_EVERY_REQUEST = True
