# Generated by Django 5.2.7 on 2025-11-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image_url',
            field=models.ImageField(upload_to='menu_images/'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
