# Generated by Django 5.2.8 on 2025-11-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allergy_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seating_choice',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Indoor', max_length=20),
        ),
    ]
