# Generated by Django 5.2.8 on 2026-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('juice', 'MCB Juice / Transfer'), ('card', 'Debit/Credit Card'), ('cash', 'Pay on Take-away')], default='cash', max_length=20),
        ),
    ]
